CREATE TABLE T_WEB_ROLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    CREATED DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(100),
    MODIFIED DATE DEFAULT SYSDATE,
    MODIFIED_BY VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER TR_WEB_ROLE_AUDIT BEFORE
    INSERT OR UPDATE ON T_WEB_ROLE
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := F_GET_CURRENT_USER();
        :NEW.MODIFIED_BY := F_GET_CURRENT_USER();
    END IF;

    IF UPDATING THEN
        :NEW.MODIFIED_BY := F_GET_CURRENT_USER();
        :NEW.MODIFIED := SYSDATE;
    END IF;

END;