CREATE TABLE T_CABLETYPE (
    ID          NUMBER
        GENERATED ALWAYS AS IDENTITY,
    CTYPE       VARCHAR(50) NOT NULL,
    DIM         VARCHAR(50) NOT NULL,
    CREATED     DATE DEFAULT SYSDATE,
    CREATED_BY  VARCHAR(100),
    MODIFIED    DATE DEFAULT SYSDATE,
    MODIFIED_BY VARCHAR(100)
);

CREATE TRIGGER TR_CABLETYPE_AUDIT BEFORE
    INSERT OR UPDATE ON T_CABLETYPE
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := F_GET_CURRENT_USER();
        :NEW.MODIFIED_BY := F_GET_CURRENT_USER();
    END IF;

    IF UPDATING THEN
        :NEW.MODIFIED_BY := F_GET_CURRENT_USER();
        :NEW.MODIFIED := SYSDATE;
    END IF;

END;
