CREATE TABLE T_DRUM (
    ID               NUMBER
        GENERATED ALWAYS AS IDENTITY,
    TNAME            VARCHAR(50) NOT NULL,
    CABLETYPE_ID     NUMBER NOT NULL,
    DRUM_RECIVED     DATE,
    LENGTH_RECIVED   NUMBER,
    LENGTH_LOST      NUMBER,
    USE_METERMARKING CHAR(1) DEFAULT '1',
    COMMENT_FOREMAN  VARCHAR(4000),
    COMMENT_STORAGE  VARCHAR(4000),
    LOCATION         VARCHAR(100),
    LOCATION_COMMENT VARCHAR(500),
    CREATED          DATE DEFAULT SYSDATE,
    CREATED_BY       VARCHAR(100),
    MODIFIED         DATE DEFAULT SYSDATE,
    MODIFIED_BY      VARCHAR(100),
    FOREIGN KEY (CABLETYPE_ID) REFERENCES T_CABLETYPE(ID)
);

CREATE TRIGGER TR_DRUM_AUDIT BEFORE
    INSERT OR UPDATE ON t_DRUM
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := F_GET_CURRENT_USER();
        :NEW.MODIFIED_BY := F_GET_CURRENT_USER();
    END IF;

    IF UPDATING THEN
        :NEW.MODIFIED_BY := F_GET_CURRENT_USER();
        :NEW.MODIFIED := SYSDATE;
    END IF;

END;
