CREATE OR REPLACE VIEW AI_DRUM AS
SELECT 
    A.ID,
    A.TNAME,
    A.CABLETYPE_ID,
    B.CTYPE || ' - ' || B.DIM CABLETYPE,
    A.DRUM_RECIVED,
    A.LENGTH_RECIVED,
    A.LENGTH_LOST,
    A.USE_METERMARKING,
    A.COMMENT_FOREMAN,
    A.COMMENT_STORAGE,
    A.LOCATION,
    A.LOCATION_COMMENT,
    A.CREATED,
    A.CREATED_BY,
    A.MODIFIED,
    A.MODIFIED_BY
FROM
    T_DRUM A
    LEFT JOIN T_CABLETYPE B ON B.ID = A.CABLETYPE_ID;



CREATE OR REPLACE TRIGGER TRG_AI_DRUMS INSTEAD OF
    INSERT OR UPDATE OR DELETE ON AI_DRUM
    FOR EACH ROW
BEGIN
-- INSERTING
    IF INSERTING THEN
        INSERT INTO T_DRUM (

            TNAME,
            CABLETYPE_ID,
            DRUM_RECIVED,
            LENGTH_RECIVED,
            LENGTH_LOST,
            USE_METERMARKING,
            COMMENT_FOREMAN,
            COMMENT_STORAGE,
            LOCATION,
            LOCATION_COMMENT

        ) VALUES (

            :NEW.TNAME,
            :NEW.CABLETYPE_ID,
            :NEW.DRUM_RECIVED,
            :NEW.LENGTH_RECIVED,
            :NEW.LENGTH_LOST,
            :NEW.USE_METERMARKING,
            :NEW.COMMENT_FOREMAN,
            :NEW.COMMENT_STORAGE,
            :NEW.LOCATION,
            :NEW.LOCATION_COMMENT
      
        );

    END IF;

    -- UPDATING
    IF UPDATING THEN
        UPDATE T_DRUM
        SET
            TNAME = :NEW.TNAME,
            CABLETYPE_ID = :NEW.CABLETYPE_ID,
            DRUM_RECIVED = :NEW.DRUM_RECIVED,
            LENGTH_RECIVED = :NEW.LENGTH_RECIVED,
            LENGTH_LOST = :NEW.LENGTH_LOST,
            USE_METERMARKING = :NEW.USE_METERMARKING,
            COMMENT_FOREMAN = :NEW.COMMENT_FOREMAN,
            COMMENT_STORAGE = :NEW.COMMENT_STORAGE,
            LOCATION = :NEW.LOCATION,
            LOCATION_COMMENT = :NEW.LOCATION_COMMENT

        WHERE
            ID = :OLD.ID;

    END IF;
    
    -- DELETING
    IF DELETING THEN
        DELETE FROM T_DRUM
        WHERE
            ID = :OLD.ID;

    END IF;
END;